extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "react-app"
  - "react-app/jest"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars": "off"
